# Use an official Node.js runtime as a parent image (multi-stage build)
FROM node:18-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Set the NODE_OPTIONS environment variable for the build process
ENV NODE_OPTIONS="--openssl-legacy-provider"

# Build the React app
RUN npm run build

# Stage 2: Serve the static files with Nginx
FROM nginx:stable-alpine

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
